# Generated by Django 5.2.8 on 2025-11-26 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='bot.city'),
            preserve_default=False,
        ),
    ]
